const fs = require('fs');
const path = require('path');

// --- SINGLE SOURCE OF TRUTH ---
const portSettings = {
  Http: 8080,
  Https: 0, // Not used in dev
  Vite: 5173,
  ViteProxy: 8080,
  Database: 5432,
  S3: 9000,
  S3Console: 9001
};

// --- Generate .env file for Docker Compose ---
// The .env file should be at the project root, so we navigate up one level.
const envPath = path.join(__dirname, '..', '.env');
const envContent = `
# This file is auto-generated by build-config.js. DO NOT EDIT.

# NGINX Proxy Port
HTTP_PORT=${portSettings.Http}

# Vite Dev Server Port
VITE_PORT=${portSettings.Vite}

# PostgreSQL Database Port
DB_PORT=${portSettings.Database}

# MinIO S3 API Port
S3_PORT=${portSettings.S3}

# MinIO Console Port
S3_CONSOLE_PORT=${portSettings.S3Console}
`.trim();

fs.writeFileSync(envPath, envContent);
console.log(`Successfully generated ${envPath}`);

// --- Generate appsettings.Ports.json for the .NET Application ---
const jsonContent = JSON.stringify({ PortSettings: portSettings }, null, 2);
const jsonPath = path.join(__dirname, 'appsettings.Ports.json');
fs.writeFileSync(jsonPath, jsonContent);
console.log(`Successfully generated ${jsonPath}`);